WHENEVER SQLERROR CONTINUE

----------------------------------------------------------------------
/*
 Created By   : IBM
 Creation Date: 10-May-2017
 Filename     : XXMIG_APPS_SYNONYMS.sql
 Description  : APPS Synonym Creation Script (Run from Custom Schema)

 Change History:

 Date         Version#  Name              Remarks
 -----------  --------  ----------------  ----------------------------
 10-May-2017  1.0       IBM               Initial Creation (AIC-Q2-02)
*/
----------------------------------------------------------------------

CREATE OR REPLACE SYNONYM APPS.XXMIG_MIGRATION_SETUP_TBL FOR XXMIG_MIGRATION_SETUP_TBL;
CREATE OR REPLACE SYNONYM APPS.XXMIG_BUSINESS_ENTITIES_TBL FOR XXMIG_BUSINESS_ENTITIES_TBL;
CREATE OR REPLACE SYNONYM APPS.XXMIG_MAPPINGS_TBL FOR XXMIG_MAPPINGS_TBL;
CREATE OR REPLACE SYNONYM APPS.XXMIG_EXTRACTS_TBL FOR XXMIG_EXTRACTS_TBL;
CREATE OR REPLACE SYNONYM APPS.XXMIG_TRANSFORMATION_ID_SEQ FOR XXMIG_TRANSFORMATION_ID_SEQ;
CREATE OR REPLACE SYNONYM APPS.XXMIG_BUSINESS_ENTITY_ID_SEQ FOR XXMIG_BUSINESS_ENTITY_ID_SEQ;
CREATE OR REPLACE SYNONYM APPS.XXMIG_MAPPING_ID_SEQ FOR XXMIG_MAPPING_ID_SEQ;
CREATE OR REPLACE SYNONYM APPS.XXMIG_EXTRACTION_ID_SEQ FOR XXMIG_EXTRACTION_ID_SEQ;
CREATE OR REPLACE SYNONYM APPS.XXMIG_FBDI_CONV_UTILS_PKG FOR XXMIG_FBDI_CONV_UTILS_PKG;

SHOW ERR

EXIT