WHENEVER SQLERROR CONTINUE

----------------------------------------------------------------------
/*
 Created By   : IBM
 Creation Date: 10-May-2017
 Filename     : XXMIG_EXTRACTS_TBL.sql
 Description  : Table Creation Script

 Change History:

 Date         Version#  Name              Remarks
 -----------  --------  ----------------  ----------------------------
 10-May-2017  1.0       IBM               Initial Creation (AIC-Q2-02)
*/
----------------------------------------------------------------------

CREATE TABLE XXMIG_EXTRACTS_TBL
(
  EXTRACTION_ID NUMBER
 ,EXTRACTED_ON DATE
 ,EXTRACTION_STATUS VARCHAR2(10)
 ,BUSINESS_ENTITY_ID NUMBER
 ,USER_LABEL VARCHAR2(100)
 ,EXTRACT_FILE BLOB
 ,EXTRACT_FILE_NAME VARCHAR2(100)
 ,LOG_FILE BLOB
 ,LOG_FILE_NAME VARCHAR2(100)
 ,MIME_TYPE VARCHAR2(255)
 ,CHARACTER_SET VARCHAR2(128)
 ,CREATION_DATE DATE
 ,CREATED_BY NUMBER
 ,LAST_UPDATE_DATE DATE
 ,UPDATED_BY NUMBER
 ,CONSTRAINT EXTRACTION_PK PRIMARY KEY (EXTRACTION_ID)
 ,CONSTRAINT BUSINESS_ENTITY_FK2 FOREIGN KEY (BUSINESS_ENTITY_ID)
    REFERENCES XXMIG_BUSINESS_ENTITIES_TBL(BUSINESS_ENTITY_ID)
);

SHOW ERR

GRANT ALL ON XXMIG_EXTRACTS_TBL TO APPS;

CREATE OR REPLACE SYNONYM APPS.XXMIG_EXTRACTS_TBL FOR XXMIG_EXTRACTS_TBL;

EXIT